# Generated by Django 6.0.1 on 2026-01-26 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gellary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gellary_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=None)),
                ('year', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
