# Generated by Django 6.0.1 on 2026-01-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_gellary'),
    ]

    operations = [
        migrations.AddField(
            model_name='gellary',
            name='image1',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='gellary',
            name='image2',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='gellary',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
