# Generated by Django 6.0.1 on 2026-01-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_gellary_image1_gellary_image2_alter_gellary_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('office_hours', models.CharField(max_length=50)),
                ('day_off', models.CharField(max_length=30)),
                ('house_no', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
    ]
