# Generated by Django 6.0.1 on 2026-01-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_company_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_info',
            name='block',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='company_info',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
