# Generated by Django 6.0.1 on 2026-01-26 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_company_info_block_company_info_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_info',
            old_name='day_off',
            new_name='friday',
        ),
    ]
