# Generated by Django 6.0.1 on 2026-01-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_day_off_company_info_friday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_info',
            name='district',
            field=models.CharField(max_length=60),
        ),
    ]
