# Generated by Django 6.0.1 on 2026-01-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_tittle', models.CharField(max_length=50)),
                ('goal_descriptions_1', models.TextField(null=True)),
                ('goal_descriptions_2', models.TextField(null=True)),
            ],
        ),
    ]
