# Generated by Django 6.0.1 on 2026-01-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='sub_title_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='sub_title_2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
