# Generated by Django 6.0.1 on 2026-01-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_goal_sub_title_1_goal_sub_title_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='help_request_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(null=True)),
                ('business_name', models.CharField(max_length=50)),
                ('message', models.TextField(null=True)),
            ],
        ),
    ]
