# Generated by Django 6.0.1 on 2026-01-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_help_request_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('descriptions', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
