# Generated by Django 6.0.1 on 2026-01-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_about_paragraph'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='about/')),
                ('descriptions', models.TextField(null=True)),
            ],
        ),
    ]
