# Generated by Django 6.0.1 on 2026-01-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_about_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_album',
            name='image',
        ),
        migrations.AddField(
            model_name='about_album',
            name='image_1',
            field=models.ImageField(null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='about_album',
            name='image_2',
            field=models.ImageField(null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='about_album',
            name='image_3',
            field=models.ImageField(null=True, upload_to='about/'),
        ),
    ]
