# Generated by Django 6.0.1 on 2026-01-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_about_album_image_about_album_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_info',
            name='cirtificate',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
