# Generated by Django 6.0.1 on 2026-01-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_company_info_cirtificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Co_sponsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(null=True, upload_to='image/')),
                ('image_2', models.ImageField(null=True, upload_to='image/')),
                ('image_4', models.ImageField(null=True, upload_to='image/')),
                ('image_5', models.ImageField(null=True, upload_to='image/')),
            ],
        ),
    ]
