# Generated by Django 6.0.1 on 2026-01-28 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_co_sponsers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About_paragraph',
            new_name='AboutParagraph',
        ),
    ]
