# Generated by Django 6.0.1 on 2026-01-28 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_rename_about_paragraph_aboutparagraph'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='about_album',
            new_name='AboutAlbum',
        ),
    ]
