# Generated by Django 6.0.1 on 2026-01-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_rename_about_album_aboutalbum'),
    ]

    operations = [
        migrations.AddField(
            model_name='co_sponsers',
            name='image_3',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
