# Generated by Django 6.0.1 on 2026-01-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_co_sponsers_image_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundersInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founder_name', models.CharField(max_length=50)),
                ('founder_image', models.ImageField(null=True, upload_to='image/')),
                ('designation', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='company_info',
            name='block',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company_info',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='company_info',
            name='friday',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='company_info',
            name='house_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='company_info',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
