# Generated by Django 6.0.1 on 2026-01-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_foundersinfo_alter_company_info_block_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SispabExecutiveCom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
            ],
        ),
    ]
