# Generated by Django 6.0.1 on 2026-01-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_sispabexecutivecom'),
    ]

    operations = [
        migrations.AddField(
            model_name='sispabexecutivecom',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
