# Generated by Django 6.0.1 on 2026-01-30 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_sispabexecutivecom_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sispabexecutivecom',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sispabexecutivecom',
            name='position',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
