# Generated by Django 6.0.1 on 2026-01-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_gellary_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousExecutiveCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('position', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(null=True, upload_to='image/')),
            ],
        ),
    ]
