# Generated by Django 6.0.1 on 2026-01-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_blog_image_alter_blog_date_alter_blog_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('issue', models.TextField(null=True)),
                ('suggetion', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='help_request_form',
            new_name='Contact_list',
        ),
    ]
