# Generated by Django 6.0.1 on 2026-01-30 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_complain_rename_help_request_form_contact_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Complain',
            new_name='Complain_list',
        ),
    ]
