# Generated by Django 6.0.1 on 2026-01-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_rename_complain_complain_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='url',
        ),
        migrations.AddField(
            model_name='events',
            name='url_1',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='url_2',
            field=models.URLField(null=True),
        ),
    ]
