# Generated by Django 6.0.1 on 2026-01-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_remove_events_url_events_url_1_events_url_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events_Meetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url_1', models.URLField(null=True)),
                ('url_2', models.URLField(null=True)),
                ('url_3', models.URLField(null=True)),
                ('url_4', models.URLField(null=True)),
                ('url_5', models.URLField(null=True)),
                ('url_6', models.URLField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
