# Generated by Django 6.0.1 on 2026-01-31 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_events_meetings'),
    ]

    operations = [
        migrations.AddField(
            model_name='previousexecutivecommittee',
            name='company',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='previousexecutivecommittee',
            name='designation',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
