# Generated by Django 6.0.1 on 2026-02-01 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_previousexecutivecommittee_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('membership_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='accounts.membershiprules')),
            ],
        ),
    ]
