# Generated by Django 6.0.1 on 2026-02-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_membershiprules_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiprules',
            name='rules',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='membershiprules',
            name='status',
            field=models.BooleanField(null=True),
        ),
        migrations.DeleteModel(
            name='Rule',
        ),
    ]
