# Generated by Django 6.0.1 on 2026-02-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_membershiprules_rules_membershiprules_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='membershiprules',
            name='rules',
        ),
        migrations.RemoveField(
            model_name='membershiprules',
            name='status',
        ),
    ]
