# Generated by Django 6.0.1 on 2026-02-02 03:24

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_rules_remove_membershiprules_rules_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
