# Generated by Django 6.0.1 on 2026-02-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_alter_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(null=True, upload_to='news/')),
                ('date', models.DateField(null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='events',
            name='url_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='url_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events_meetings',
            name='url_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events_meetings',
            name='url_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events_meetings',
            name='url_3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events_meetings',
            name='url_4',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events_meetings',
            name='url_5',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events_meetings',
            name='url_6',
            field=models.URLField(blank=True, null=True),
        ),
    ]
