# Generated by Django 6.0.1 on 2026-02-03 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_news_alter_events_url_1_alter_events_url_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='goal_descriptions_1',
            new_name='goal_descriptions',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='goal_descriptions_2',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='sub_title_1',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='sub_title_2',
        ),
    ]
