# Generated by Django 6.0.1 on 2026-02-07 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_rename_goal_descriptions_1_goal_goal_descriptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gellary',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
