# Generated by Django 6.0.1 on 2026-02-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_corevalues'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='events',
            name='description',
        ),
        migrations.RemoveField(
            model_name='events',
            name='title',
        ),
    ]
