# Generated by Django 6.0.1 on 2026-02-07 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_eventtitle_remove_events_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.eventtitle'),
        ),
        migrations.AlterField(
            model_name='eventtitle',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
