# Generated by Django 6.0.1 on 2026-02-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_events_title_alter_eventtitle_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=50)),
                ('num_of_vacancy', models.IntegerField(blank=True, null=True)),
                ('loction_add', models.TextField(null=True)),
                ('deadline_date', models.DateField(null=True)),
                ('job_type', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
