# Generated by Django 5.0.5 on 2026-02-08 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_delete_rules_membershiprules_rules_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events_meetings',
            old_name='url_1',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='events_meetings',
            name='url_2',
        ),
        migrations.RemoveField(
            model_name='events_meetings',
            name='url_3',
        ),
        migrations.RemoveField(
            model_name='events_meetings',
            name='url_4',
        ),
        migrations.RemoveField(
            model_name='events_meetings',
            name='url_5',
        ),
        migrations.RemoveField(
            model_name='events_meetings',
            name='url_6',
        ),
    ]
