# Generated by Django 5.0.5 on 2026-02-09 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_agregator_alter_aboutalbum_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agregator',
        ),
    ]
