# Generated by Django 5.0.5 on 2026-02-09 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_delete_agregator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agregator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('company_name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Bangladesh phone number (e.g. 017XXXXXXXX or +88017XXXXXXXX)', regex='^(?:\\+8801|01)[3-9]\\d{8}$')])),
                ('address', models.TextField(null=True)),
            ],
        ),
    ]
