# Generated by Django 5.0.5 on 2026-02-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_agregator'),
    ]

    operations = [
        migrations.AddField(
            model_name='agregator',
            name='brtc_licence_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
