# Generated by Django 5.0.5 on 2026-02-10 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_aggregator_delete_agregator'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain_list',
            name='aggregator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.aggregator'),
        ),
    ]
