# Generated by Django 5.0.5 on 2026-02-10 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_complain_list_aggregator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='year',
        ),
    ]
