# Generated by Django 5.0.5 on 2026-02-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_remove_media_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
