# Generated by Django 5.0.5 on 2026-02-10 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_media_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Media',
            new_name='PhotoGallery',
        ),
    ]
