# Generated by Django 5.0.5 on 2026-02-10 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_rename_media_photogallery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhotoGallery',
            new_name='Media',
        ),
    ]
