# Generated by Django 5.0.5 on 2026-02-10 07:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_rename_photogallery_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplainList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Bangladesh phone number (e.g. 017XXXXXXXX or +88017XXXXXXXX)', regex='^(?:\\+8801|01)[3-9]\\d{8}$')])),
                ('issue', models.TextField(blank=True, null=True)),
                ('suggestion', models.CharField(blank=True, max_length=50, null=True)),
                ('aggregator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.aggregator')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/')),
                ('year', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='complain_list',
            name='aggregator',
        ),
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.DeleteModel(
            name='Complain_list',
        ),
    ]
