# Generated by Django 5.0.5 on 2026-02-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_photoalbum_remove_photo_title_photo_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoalbum',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
