# Generated by Django 5.2.5 on 2026-02-15 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_alter_photoalbum_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=50)),
                ('descriptions', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='media/')),
            ],
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
