# Generated by Django 5.0.5 on 2026-02-15 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_heroarea_delete_goal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='career',
            old_name='loction_add',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='career',
            old_name='position_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='career',
            name='deadline_date',
        ),
        migrations.RemoveField(
            model_name='career',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='career',
            name='num_of_vacancy',
        ),
    ]
