# Generated by Django 5.0.5 on 2026-02-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0066_rename_loction_add_career_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregator',
            name='designation',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
