# Generated by Django 5.0.5 on 2026-02-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_meetingcall'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingcall',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
