# Generated by Django 5.0.5 on 2026-02-15 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0069_meetingcall_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='meetingcall',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.meetingtitle'),
        ),
    ]
