# Generated by Django 5.0.5 on 2026-02-16 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_meetingtitle_alter_meetingcall_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_list',
            name='business_name',
        ),
    ]
