# Generated by Django 5.0.5 on 2026-02-16 10:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0073_meetingtitle_image_alter_aboutalbum_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregator',
            name='phone',
            field=models.CharField(blank=True, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Bangladesh phone number (e.g. 017XXXXXXXX or +88017XXXXXXXX)', regex='^(?:\\+8801|01)[3-9]\\d{8}$')]),
        ),
    ]
