# Generated by Django 5.0.5 on 2026-02-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0074_alter_aggregator_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingcall',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
