# Generated by Django 5.0.5 on 2026-02-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0075_meetingcall_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='corevalues',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='mission',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='vision',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
