# Generated by Django 5.0.5 on 2026-02-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0076_corevalues_image_mission_image_vision_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingcall',
            name='expire_date',
            field=models.DateField(null=True),
        ),
    ]
