# Generated by Django 5.0.5 on 2026-02-17 08:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0077_meetingcall_expire_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingcall',
            name='expire_date',
        ),
        migrations.AddField(
            model_name='meetingtitle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetingtitle',
            name='expire_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='meetingcall',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingcall',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='meetingcall',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
