# Generated by Django 6.0.1 on 2026-02-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0079_alter_aboutalbum_id_alter_aboutparagraph_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingtitle',
            name='expire_date',
            field=models.DateTimeField(null=True),
        ),
    ]
