# Generated by Django 6.0.1 on 2026-02-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0080_alter_meetingtitle_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregator',
            name='is_aggregator',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
