# Generated by Django 6.0.1 on 2026-02-19 08:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0081_aggregator_is_aggregator'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('person_name', models.CharField(max_length=50)),
                ('designation', models.CharField(blank=True, max_length=50, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Bangladesh phone number (e.g. 017XXXXXXXX or +88017XXXXXXXX)', regex='^(?:\\+8801|01)[3-9]\\d{8}$')])),
                ('is_aggregrator', models.CharField(blank=True, max_length=3, null=True)),
                ('brtc_licence_no', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
