# Generated by Django 5.0.5 on 2026-02-19 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0083_tempmember_otp_tempmember_otp_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tempmember',
            old_name='is_aggregrator',
            new_name='is_aggregator',
        ),
    ]
