# Generated by Django 5.0.5 on 2026-02-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0085_alter_tempmember_email_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempmember',
            name='is_aggregator',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='tempmember',
            name='status',
            field=models.CharField(choices=[('pending', 'pending')], default='pending', max_length=20),
        ),
    ]
