# Generated by Django 5.0.5 on 2026-02-21 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0086_alter_tempmember_is_aggregator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tempmember',
            old_name='email_address',
            new_name='email',
        ),
    ]
