# Generated by Django 5.0.5 on 2026-02-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0087_rename_email_address_tempmember_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempmember',
            name='is_aggregator',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
