# Generated by Django 5.0.5 on 2026-02-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0090_tempmember_appoinment_letter_tempmember_cv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregator',
            name='member_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='tempmember',
            name='member_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
