# Generated by Django 5.0.5 on 2026-02-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0091_aggregator_member_id_tempmember_member_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempmember',
            name='member_id',
        ),
        migrations.AlterField(
            model_name='aggregator',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tempmember',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
