# Generated by Django 6.0.1 on 2026-02-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0093_aggregator_tread_licence_no_alter_aboutalbum_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100, unique=True)),
                ('meta_title', models.CharField(max_length=255)),
                ('meta_description', models.TextField()),
                ('meta_keywords', models.TextField(blank=True)),
                ('meta_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
                ('meta_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
