# Generated by Django 6.0.1 on 2026-03-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0094_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregator',
            name='company_logo',
            field=models.ImageField(null=True, upload_to='Aggregator/'),
        ),
        migrations.AlterField(
            model_name='aggregator',
            name='member_id',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
