# Generated by Django 6.0.1 on 2026-03-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0095_aggregator_company_logo_alter_aggregator_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregator',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'AGM'), (2, 'AGU')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='aggregator',
            name='member_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddConstraint(
            model_name='aggregator',
            constraint=models.UniqueConstraint(fields=('user_type', 'member_id'), name='unique_member_per_type'),
        ),
    ]
