# Generated by Django 6.0.1 on 2026-03-02 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0096_aggregator_user_type_alter_aggregator_member_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregator',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
