# Generated by Django 6.0.1 on 2026-03-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0097_aggregator_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregator',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
