# Generated by Django 6.0.1 on 2026-03-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0098_aggregator_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregator',
            name='status',
            field=models.IntegerField(choices=[(1, 'AGM'), (2, 'AGU')], editable=False, null=True),
        ),
    ]
