# Generated by Django 6.0.1 on 2026-03-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0099_aggregator_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregator',
            name='status',
            field=models.IntegerField(choices=[(1, 'AGM'), (2, 'AGU')], default=1, editable=False, null=True),
        ),
    ]
