# Generated by Django 5.0.5 on 2026-03-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0101_alter_aboutalbum_id_alter_aboutparagraph_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempmember',
            name='n_id',
            field=models.CharField(max_length=22, null=True),
        ),
    ]
