# Generated by Django 6.0.1 on 2026-03-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0103_emergencyservices_govermentservices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, unique=True),
        ),
    ]
