# Generated by Django 6.0.1 on 2026-03-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0105_remove_news_date_news_created_at_news_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='photoalbum',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
