# Generated by Django 6.0.1 on 2026-03-03 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0106_photo_slug_photoalbum_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='photoalbum',
            name='slug',
        ),
    ]
