# Generated by Django 6.0.1 on 2026-03-03 09:28

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0108_photo_slug_photoalbum_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='url_1',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='events',
            name='url_2',
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=accounts.models.photo_upload_to),
        ),
    ]
