# Generated by Django 6.0.1 on 2026-03-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0109_rename_url_1_events_url_remove_events_url_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingtitle',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
