# Generated by Django 6.0.1 on 2026-03-04 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0110_meetingtitle_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_info',
            old_name='friday',
            new_name='day_off',
        ),
    ]
