# Generated by Django 6.0.1 on 2026-03-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0111_rename_friday_company_info_day_off'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='company_info',
            name='day_off',
        ),
    ]
