# Generated by Django 6.0.1 on 2026-03-04 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0112_weekend_remove_company_info_day_off'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('office_hours', models.CharField(max_length=50)),
                ('house_no', models.CharField(max_length=50)),
                ('block', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(max_length=60)),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('country', models.CharField(max_length=50)),
                ('day_off', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='accounts.weekend')),
            ],
        ),
        migrations.DeleteModel(
            name='Company_info',
        ),
    ]
