# Generated by Django 6.0.1 on 2026-03-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0113_companyinfo_delete_company_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='day_off',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='day_off',
            field=models.ManyToManyField(blank=True, related_name='companies', to='accounts.weekend'),
        ),
    ]
