# Generated by Django 6.0.1 on 2026-03-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0114_remove_companyinfo_day_off_companyinfo_day_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoalbum',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
