# Generated by Django 6.0.1 on 2026-03-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0115_photoalbum_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(max_length=200)),
                ('sponsor_email', models.EmailField(max_length=254)),
                ('sponsor_phone', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='sponsor_logo/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
