# Generated by Django 6.0.1 on 2026-03-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0116_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='company_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='designation',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
