# Generated by Django 6.0.1 on 2026-03-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0117_sponsor_company_name_sponsor_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BecomeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
