# Generated by Django 6.0.1 on 2026-03-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0118_becomemember'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingcall',
            name='payout_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='meetingcall',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment/'),
        ),
    ]
