# Generated by Django 6.0.1 on 2026-03-08 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0119_meetingcall_payout_number_meetingcall_screenshot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergencyservices',
            old_name='url',
            new_name='number',
        ),
    ]
