# Generated by Django 6.0.1 on 2026-03-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0120_rename_url_emergencyservices_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyservices',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
