# Generated by Django 6.0.1 on 2026-03-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0121_emergencyservices_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='govermentservices',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
