# Generated by Django 6.0.1 on 2026-03-12 03:51

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0123_alter_meetingtitle_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingtitle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.meeting_image_upload),
        ),
    ]
